"use strict";

// 5 pixels = 1m

var PIXELS_METER = 5;
// BOARD
var GAME_WIDTH = 1000;
var GAME_HEIGHT = 1000;
var TILE_SIZE = 50;

// VEHICLE
var VEHICLE_LENGTH = 4 * PIXELS_METER;
var VEHICLE_HEIGHT = 1 * PIXELS_METER;
var VEHICLE_WIDTH = 2 * PIXELS_METER;


// DIRECTION
var DIRECTION_N = 0;
var DIRECTION_NE = 1;
var DIRECTION_E = 2;
var DIRECTION_SE = 3;
var DIRECTION_S = 4;
var DIRECTION_SW = 5;
var DIRECTION_W = 6;
var DIRECTION_NW = 7;

// TURNING
var TURN_NONE = 'TURN_NONE';
var TURN_LEFT = 'TURN_LEFT';
var TURN_RIGHT = 'TURN_RIGHT';

//SPEED
var MAX_SPEED = 4;
var SPEED =[0, 2000, 1000, 500, 250 ];

